"""Tools for conjugation-group calculations in the Clifford hierarchy."""

from .actions import (
    ActionImageClassification,
    ConjugationAction,
    ConjugationActionTable,
    GeneratorSource,
    PauliActionClassification,
    StreamedActionImageClassification,
    StreamedConjugationGenerators,
    StreamedPauliActionClassification,
    classify_action_images,
    classify_pauli_images,
    conjugation_action,
    conjugation_action_table,
    stream_classify_action_images,
    stream_classify_pauli_images,
    stream_conjugation_generators,
)
from .benchmarking import (
    GROUP_SEARCH_BENCHMARK_SCHEMA,
    GroupSearchBenchmarkRecord,
    GroupSearchBenchmarkRun,
    GroupSearchMeasurements,
    GroupSearchOutcome,
    GroupSearchWorkload,
    build_group_search_benchmark_record,
    run_conjugation_group_benchmark,
)
from .conjugation import (
    ConjugationGroup,
    conjugate,
    generate_conjugation_group,
    generate_conjugation_groups,
    generate_next_conjugation_group,
)
from .de_silva_lautsch import verify_counterexample
from .exact_witnesses import (
    ExactPauliAction,
    ExactWitnessVerification,
    verify_numerical_witness_exact,
)
from .groups import (
    DEFAULT_SEARCH_LIMITS,
    GroupClosure,
    SearchLimits,
    StopReason,
    generate_group,
)
from .operators import (
    DEFAULT_PROJECTIVE_CONFIG,
    Gate,
    GateSet,
    ProjectiveConfig,
    canonicalize_projective,
    projective_key,
    projectively_equal,
)
from .paulis import PauliWord, recognize_pauli_word
from .standard_gates import (
    DEFAULT_PAULI_CATALOG_LIMIT,
    embed_one_qubit_gate,
    pauli_generators,
    projective_pauli_group,
)
from .witnesses import WITNESS_SCHEMA, build_numerical_witness, export_numerical_witness

__all__ = [
    "DEFAULT_PROJECTIVE_CONFIG",
    "DEFAULT_SEARCH_LIMITS",
    "DEFAULT_PAULI_CATALOG_LIMIT",
    "ActionImageClassification",
    "ConjugationAction",
    "ConjugationActionTable",
    "ConjugationGroup",
    "ExactPauliAction",
    "ExactWitnessVerification",
    "Gate",
    "GateSet",
    "GeneratorSource",
    "GROUP_SEARCH_BENCHMARK_SCHEMA",
    "GroupClosure",
    "GroupSearchBenchmarkRecord",
    "GroupSearchBenchmarkRun",
    "GroupSearchMeasurements",
    "GroupSearchOutcome",
    "GroupSearchWorkload",
    "PauliActionClassification",
    "PauliWord",
    "ProjectiveConfig",
    "SearchLimits",
    "StreamedConjugationGenerators",
    "StreamedActionImageClassification",
    "StreamedPauliActionClassification",
    "StopReason",
    "WITNESS_SCHEMA",
    "build_numerical_witness",
    "build_group_search_benchmark_record",
    "canonicalize_projective",
    "classify_action_images",
    "classify_pauli_images",
    "conjugate",
    "conjugation_action",
    "conjugation_action_table",
    "embed_one_qubit_gate",
    "export_numerical_witness",
    "generate_conjugation_group",
    "generate_conjugation_groups",
    "generate_group",
    "generate_next_conjugation_group",
    "pauli_generators",
    "projective_key",
    "projective_pauli_group",
    "projectively_equal",
    "recognize_pauli_word",
    "run_conjugation_group_benchmark",
    "stream_conjugation_generators",
    "stream_classify_action_images",
    "stream_classify_pauli_images",
    "verify_counterexample",
    "verify_numerical_witness_exact",
]
__version__ = "0.3.0"
